"""Task_description

Revision ID: 18b6df24d59b
Revises: ace1d925a1f6
Create Date: 2024-02-25 15:58:21.318095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18b6df24d59b'
down_revision: Union[str, None] = 'ace1d925a1f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('description', sa.String(), nullable=True))
    op.drop_column('tasks', 'slug')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'description')
    # ### end Alembic commands ###
